#!/bin/bash
MSG="""
<html>
    <head>

    </head>
    <body>
        <div class='container' style='margin: 0 auto; justify-contenet: center; max-width: 25vw;'>
            <div class='job-image' style='text-align: center;'>
                <img style='height: 10vh;' src='https://userinfo.surfsara.nl/sites/default/files/SURFsara_0.jpg'/>
            </div>
            <div class='job-name' style='text-align: center; font-weight: 600; font-size: 2em;'>
                JOB #$2
            </div>
            <hr/>
            <div class='job-status' style='font-weight: 300; font-size: 1.25em; text-align: center; background-color: rgb(255, 255, 255); border-spacing: 1em; padding: 0.5em; margin: 1em;'>
                $3
            </div>
            <div class='job-status' style='font-weight: 200; font-size: 1em; text-align: center; background-color: rgb(255, 255, 255); border-spacing: 1em; padding: 0.5em; margin: 1em;'>
                `date`
            </div>
            
            <hr />

            <div class='job-contents' style='background-color: rgb(241, 241, 241); line-height: 2em; padding: 2em;'>
                $4
            </div>
        </div>
    </body>
</html>
"""

echo $MSG | mail $USER -a "Content-type: text/html" -s "[$1] $3 (job #$2)"
